<a href="https://colab.research.google.com/github/ArathiKP/Learn.py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [1]:
#please type your answer below this line.
import numpy as np
mat1 = np.random.randint(0,8,(3,3)) 
mat2 = np.random.randint(10,19,(3,3))    
print("Matrix A\n" ,mat1)  
print("\nMatrix B\n" ,mat2)  
out = np.multiply.outer(mat1,mat2) 
print("Outer Products\n",out)  
dot = np.dot(mat1,mat2) 
print("Dot Products\n",dot)  
Ele = np.multiply(mat1,mat2) 
print("Element Wise\n",Ele)


Matrix A
 [[7 6 4]
 [7 3 2]
 [2 5 5]]

Matrix B
 [[14 14 12]
 [13 11 18]
 [18 15 10]]
Outer Products
 [[[[ 98  98  84]
   [ 91  77 126]
   [126 105  70]]

  [[ 84  84  72]
   [ 78  66 108]
   [108  90  60]]

  [[ 56  56  48]
   [ 52  44  72]
   [ 72  60  40]]]


 [[[ 98  98  84]
   [ 91  77 126]
   [126 105  70]]

  [[ 42  42  36]
   [ 39  33  54]
   [ 54  45  30]]

  [[ 28  28  24]
   [ 26  22  36]
   [ 36  30  20]]]


 [[[ 28  28  24]
   [ 26  22  36]
   [ 36  30  20]]

  [[ 70  70  60]
   [ 65  55  90]
   [ 90  75  50]]

  [[ 70  70  60]
   [ 65  55  90]
   [ 90  75  50]]]]
Dot Products
 [[248 224 232]
 [173 161 158]
 [183 158 164]]
Element Wise
 [[98 84 48]
 [91 33 36]
 [36 75 50]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [2]:
#please type your answer below this line.
import numpy as np  
mat = np.random.randint(0,16,(4,4)) 
print("Matrix is \n", mat)  
#adding 4(scalar)to the matrix 
scal = 2 
addScal = mat + scal 
print("\n Scalar Matrix\n",addScal)  
#matrix broadcasting 
nums = np.array([1,2,3,4]) 
mult = mat * nums 
print("\nThe Multiplication by broadcasting\n",mult)


Matrix is 
 [[13 13  4  1]
 [ 3 14  4  8]
 [12  9 12  1]
 [13  9 10 10]]

 Scalar Matrix
 [[15 15  6  3]
 [ 5 16  6 10]
 [14 11 14  3]
 [15 11 12 12]]

The Multiplication by broadcasting
 [[13 26 12  4]
 [ 3 28 12 32]
 [12 18 36  4]
 [13 18 30 40]]
