<a href="https://colab.research.google.com/github/ArathiKP/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [1]:
#please enter your code below this line.
import numpy as np 
mat = np.random.randint(0,8,(3,3)) 
print("\n The Matrix is:\n",mat) 
sum = np.sum(mat) 
print("\n Sum is :\n",sum)



 The Matrix is:
 [[6 0 2]
 [4 1 6]
 [1 6 0]]

 Sum is :
 26


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [5]:
#please enter your code below this line.
import numpy as np 
mat = np.random.randint(0,8,(3,3)) 
print("\n The Matrix is:\n",mat) 
col = np.sum(mat,axis =0) 
print("\n Sum of Columns:\n",col) 
row = np.sum(mat,axis =1) 
print("\n Sum of rows:\n",row)


 The Matrix is:
 [[2 5 2]
 [4 4 6]
 [4 5 0]]

 Sum of Columns:
 [10 14  8]

 Sum of rows:
 [ 9 14  9]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [6]:
#please enter your code belowthis line.
import numpy as np 
mat = np.random.randint(0,15,(4,4)) 
print("\n The Matrix is:\n",mat)  
min = np.min(mat) 
print("\n Minimum Value is\n",min)  
max = np.max(mat) 
print("\n Maximum Value is\n",max)  
mean = np.mean(mat) 
print("\n Minimum Value is\n",mean)


 The Matrix is:
 [[10 14  2  0]
 [ 5  5  6  3]
 [ 3  7  4 13]
 [ 9  8  1 11]]

 Minimum Value is
 0

 Maximum Value is
 14

 Minimum Value is
 6.3125


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [7]:
#please enter your code below this line.
import numpy as np 
mat = np.random.randint(0,99,(10,10)) 
print("\n The Matrix is:\n",mat) 
print("\nThe 7th row is :\n",mat[7,:])  
print("\nThe 4-8th row is :\n",mat[4:8,:]) 
print("\nThe value at (5,5) is :\n",mat[5,5])  
print("\nThe 5th column) is :\n",mat[:,5]) 
print("\nThe 2-5th column) is :\n",mat[:,2:5])



 The Matrix is:
 [[35  3  4 69 43 52 17 73 28 63]
 [29 86 72 10 58 47 88 54 71 93]
 [79  3 47 59 92 48 79 56 78 80]
 [ 2 32 56 85 14 31 93  4 36 82]
 [58 15 80  5 55 46 47 78 37  7]
 [87 12 69 93 23 71 39 59  5 93]
 [10 50 57 78 56 66 21 45 25 79]
 [90 75 64 83 23  9 59 49 27  9]
 [17 82 63 15 36 70 56 73 30 38]
 [82 44 81  6 70 55  9 72 46 82]]

The 7th row is :
 [90 75 64 83 23  9 59 49 27  9]

The 4-8th row is :
 [[58 15 80  5 55 46 47 78 37  7]
 [87 12 69 93 23 71 39 59  5 93]
 [10 50 57 78 56 66 21 45 25 79]
 [90 75 64 83 23  9 59 49 27  9]]

The value at (5,5) is :
 71

The 5th column) is :
 [52 47 48 31 46 71 66  9 70 55]

The 2-5th column) is :
 [[ 4 69 43]
 [72 10 58]
 [47 59 92]
 [56 85 14]
 [80  5 55]
 [69 93 23]
 [57 78 56]
 [64 83 23]
 [63 15 36]
 [81  6 70]]
