<a href="https://colab.research.google.com/github/ArathiKP/Learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [1]:
#please type your answer below this line.
import numpy as np  
mat = np.random.randint(0,15,(4,4)) 
print("Array\n",mat)  
print("Trace of the Array is: \n",mat.trace())


Array
 [[13  5  1  4]
 [ 9 11  1  0]
 [10  2  7  7]
 [11  9  0  0]]
Trace of the Array is: 
 31


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [2]:
#please type your answer below this line.
import numpy as np 
mat = np.array([[6,1,1],[4,-2,5],[2,8,7]]) 
print("Matix\n",mat) 
print("\nThe Inverse of Matrix is :\n",np.linalg.inv(mat))


Matix
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The Inverse of Matrix is :
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [3]:
#please type your answer below this line.
import numpy as np  
mat = np.random.randint(0,8,(3,3)) 
print("Array\n",mat) 
print("\nThe Norm of the Matrix is\n",np.linalg.norm(mat))


Array
 [[0 1 7]
 [2 0 2]
 [6 4 6]]

The Norm of the Matrix is
 12.083045973594572


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [4]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,15,(4,4)) 
print("Array\n",mat) 
print("\nThe EigenValue and EigenVectors of the Matrix is\n",np.linalg.eig(mat))

Array
 [[ 0  2  3  6]
 [14  5  6  7]
 [ 3 10  6  7]
 [ 9  0  2  1]]

The EigenValue and EigenVectors of the Matrix is
 (array([18.68641931+0.j       , -6.86020056+0.j       ,
        0.08689063+1.4594037j,  0.08689063-1.4594037j]), array([[ 0.24512269+0.j        ,  0.40972938+0.j        ,
         0.13976919+0.04571004j,  0.13976919-0.04571004j],
       [ 0.65481105+0.j        , -0.40171121+0.j        ,
         0.22598817-0.21425995j,  0.22598817+0.21425995j],
       [ 0.68572686+0.j        ,  0.54805391+0.j        ,
        -0.86536675+0.j        , -0.86536675-0.j        ],
       [ 0.20227712+0.j        , -0.60859416+0.j        ,
         0.34825985+0.10607856j,  0.34825985-0.10607856j]]))
