<a href="https://colab.research.google.com/github/ArathiKP/Learn.py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [4]:
#please type your answer below this line.
import numpy as np
mat1 = np.random.randint(0,8,(3,3)) 
mat2 = np.random.randint(10,19,(3,3))    
print("Matrix A\n" ,mat1)  
print("\nMatrix B\n" ,mat2)  
out = np.multiply.outer(mat1,mat2) 
print("Outer Products\n",out)  
dot = np.dot(mat1,mat2) 
print("Dot Products\n",dot)  
Ele = np.multiply(mat1,mat2) 
print("Element Wise\n",Ele)



Matrix A
 [[5 1 2]
 [5 5 7]
 [2 6 6]]

Matrix B
 [[13 18 11]
 [15 15 18]
 [17 12 12]]
Outer Products
 [[[[ 65  90  55]
   [ 75  75  90]
   [ 85  60  60]]

  [[ 13  18  11]
   [ 15  15  18]
   [ 17  12  12]]

  [[ 26  36  22]
   [ 30  30  36]
   [ 34  24  24]]]


 [[[ 65  90  55]
   [ 75  75  90]
   [ 85  60  60]]

  [[ 65  90  55]
   [ 75  75  90]
   [ 85  60  60]]

  [[ 91 126  77]
   [105 105 126]
   [119  84  84]]]


 [[[ 26  36  22]
   [ 30  30  36]
   [ 34  24  24]]

  [[ 78 108  66]
   [ 90  90 108]
   [102  72  72]]

  [[ 78 108  66]
   [ 90  90 108]
   [102  72  72]]]]
Dot Products
 [[114 129  97]
 [259 249 229]
 [218 198 202]]
Element Wise
 [[ 65  18  22]
 [ 75  75 126]
 [ 34  72  72]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [3]:
#please type your answer below this line.
import numpy as np  
mat = np.random.randint(0,16,(4,4)) 
print("Matrix is \n", mat)  
#adding 4(scalar)to the matrix 
scal = 2 
addScal = mat + scal 
print("\n Scalar Matrix\n",addScal)  
#matrix broadcasting 
nums = np.array([1,2,3,4]) 
mult = mat * nums 
print("\nThe Multiplication by broadcasting\n",mult)



Matrix is 
 [[ 4  2  2 12]
 [13  9  0 12]
 [11 14 15  2]
 [ 0  6 10  1]]

 Scalar Matrix
 [[ 6  4  4 14]
 [15 11  2 14]
 [13 16 17  4]
 [ 2  8 12  3]]

The Multiplication by broadcasting
 [[ 4  4  6 48]
 [13 18  0 48]
 [11 28 45  8]
 [ 0 12 30  4]]
